# Generated by Django 2.1.4 on 2020-02-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(),
        ),
    ]
