# Generated by Django 2.1.4 on 2020-02-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200214_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='score',
            new_name='user_rating',
        ),
    ]
