# Generated by Django 3.0.3 on 2020-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='picture/no_image.jpg', upload_to='media/'),
        ),
    ]
